This notebook contains code regarding the final merging of all complete county attribute datasets (2012, 2016, 2019 & 2023) and subsequent export for futher visualization.

In [1]:
import pandas as pd

In [2]:
# Read in the combined 2012, 2016, 2019 dataset and the 2023 dataset for merge
# 2023 dataset 
county_2023 = pd.read_csv("Resources/2023_County_Final_With_Segments_And_Predictions.csv")
county_2023

,Year,County,% Male,% Female,% Male > 18 Years Old,% Female > 18 Years Old,% White,% Black or African American,% American Indian and Alaska Native,% Asian,...,Nonveteran Labor Force Participation Rate (%),Nonveteran Unemployment Rate (%),% Nonveteran Population With Income Below Poverty Level (Past 12 Months),% Nonveteran Population With Any Disability,Birth Rate Per 1000 Women (15-19 Years Old),Birth Rate Per 1000 Women (20-34 Years Old),Birth Rate Per 1000 Women (35-50 Years Old),Received Public Assistance Income Rate Per 1000 Women (Past 12 Months),Segment,winning_party D:0 R:1
0,2023,ADAMS,0.492,0.508,0.490,0.510,0.882,0.013,0.004,0.008,...,0.821,0.035,0.079,0.141,0.000000,94.000000,49.000000,97.555556,2,1
1,2023,ALLEGHENY,0.488,0.512,0.482,0.518,0.759,0.125,0.001,0.042,...,0.811,0.039,0.110,0.144,9.000000,79.000000,35.000000,189.000000,0,0
2,2023,ARMSTRONG,0.499,0.501,0.497,0.503,0.951,0.006,0.000,0.001,...,0.769,0.027,0.106,0.186,30.000000,123.000000,9.000000,68.000000,1,1
3,2023,BEAVER,0.495,0.505,0.487,0.513,0.859,0.054,0.002,0.003,...,0.801,0.027,0.100,0.174,0.000000,67.000000,26.000000,222.000000,2,1
4,2023,BERKS,0.495,0.505,0.490,0.510,0.692,0.041,0.007,0.014,...,0.786,0.052,0.104,0.155,6.000000,102.000000,45.000000,57.000000,2,0
5,2023,BLAIR,0.497,0.503,0.492,0.508,0.905,0.024,0.000,0.008,...,0.757,0.032,0.147,0.189,0.000000,64.000000,49.000000,0.000000,1,1
6,2023,BUCKS,0.495,0.505,0.490,0.510,0.809,0.032,0.002,0.050,...,0.823,0.036,0.066,0.129,0.000000,84.000000,30.000000,199.000000,0,0
7,2023,BUTLER,0.498,0.502,0.494,0.506,0.928,0.009,0.003,0.014,...,0.781,0.043,0.087,0.145,0.000000,82.000000,34.000000,0.000000,2,0
8,2023,CAMBRIA,0.498,0.502,0.494,0.506,0.906,0.032,0.000,0.004,...,0.748,0.042,0.120,0.216,7.000000,107.000000,39.000000,27.000000,1,1
9,2023,CARBON,0.510,0.490,0.508,0.492,0.872,0.023,0.016,0.007,...,0.773,0.065,0.118,0.200,6.589744,89.384615,32.102564,97.555556,1,1
10,2023,CENTRE,0.521,0.479,0.524,0.476,0.839,0.037,0.001,0.063,...,0.650,0.036,0.212,0.132,0.000000,74.000000,60.000000,59.000000,1,0
11,2023,CHESTER,0.495,0.505,0.492,0.508,0.764,0.051,0.000,0.070,...,0.836,0.029,0.061,0.109,2.000000,69.000000,50.000000,157.000000,0,0
12,2023,CLEARFIELD,0.521,0.479,0.522,0.478,0.935,0.022,0.001,0.003,...,0.734,0.020,0.155,0.192,11.000000,80.000000,28.000000,0.000000,1,1
13,2023,COLUMBIA,0.488,0.512,0.485,0.515,0.912,0.018,0.001,0.016,...,0.788,0.057,0.119,0.114,0.000000,48.000000,8.000000,97.555556,2,1
14,2023,CRAWFORD,0.493,0.507,0.491,0.509,0.934,0.015,0.001,0.003,...,0.752,0.031,0.112,0.191,0.000000,69.000000,15.000000,0.000000,1,1
15,2023,CUMBERLAND,0.497,0.503,0.494,0.506,0.811,0.043,0.000,0.057,...,0.813,0.028,0.084,0.143,0.000000,84.000000,24.000000,0.000000,2,0
16,2023,DAUPHIN,0.489,0.511,0.482,0.518,0.624,0.185,0.006,0.070,...,0.815,0.046,0.114,0.152,0.000000,100.000000,24.000000,27.000000,2,0
17,2023,DELAWARE,0.485,0.515,0.477,0.523,0.626,0.225,0.001,0.062,...,0.788,0.060,0.102,0.154,26.000000,81.000000,38.000000,31.000000,0,0
18,2023,ERIE,0.503,0.497,0.494,0.506,0.829,0.077,0.001,0.021,...,0.740,0.040,0.130,0.190,0.000000,91.000000,45.000000,27.000000,1,0
19,2023,FAYETTE,0.497,0.503,0.495,0.505,0.902,0.039,0.001,0.005,...,0.699,0.036,0.179,0.225,0.000000,121.000000,15.000000,94.000000,1,1
20,2023,FRANKLIN,0.491,0.509,0.489,0.511,0.856,0.025,0.002,0.013,...,0.807,0.046,0.078,0.178,0.000000,123.000000,13.000000,186.000000,2,1
21,2023,INDIANA,0.500,0.500,0.500,0.500,0.931,0.027,0.000,0.003,...,0.686,0.056,0.167,0.183,0.000000,114.000000,17.000000,0.000000,1,1
22,2023,LACKAWANNA,0.493,0.507,0.484,0.516,0.803,0.037,0.000,0.032,...,0.738,0.029,0.164,0.198,9.000000,109.000000,25.000000,193.000000,1,0
23,2023,LANCASTER,0.490,0.510,0.484,0.516,0.807,0.038,0.002,0.022,...,0.826,0.031,0.076,0.149,1.000000,117.000000,61.000000,110.000000,2,1
24,2023,LAWRENCE,0.488,0.512,0.482,0.518,0.891,0.044,0.001,0.003,...,0.754,0.043,0.129,0.200,20.000000,67.000000,25.000000,0.000000,1,1
25,2023,LEBANON,0.495,0.505,0.488,0.512,0.809,0.031,0.000,0.021,...,0.828,0.022,0.078,0.146,0.000000,80.000000,21.000000,74.000000,2,0
26,2023,LEHIGH,0.493,0.507,0.487,0.513,0.613,0.062,0.007,0.039,...,0.795,0.048,0.110,0.150,0.000000,71.000000,30.000000,39.000000,2,0
27,2023,LUZERNE,0.499,0.501,0.496,0.504,0.744,0.051,0.003,0.013,...,0.752,0.047,0.150,0.191,0.000000,83.000000,22.000000,134.000000,1,1
28,2023,LYCOMING,0.493,0.507,0.489,0.511,0.885,0.032,0.008,0.009,...,0.783,0.048,0.118,0.188,40.000000,105.000000,17.000000,22.000000,1,1
29,2023,MERCER,0.497,0.503,0.490,0.510,0.884,0.042,0.002,0.006,...,0.737,0.051,0.104,0.170,0.000000,67.000000,34.000000,61.000000,1,1
30,2023,MONROE,0.510,0.490,0.499,0.501,0.626,0.144,0.002,0.027,...,0.770,0.067,0.089,0.186,0.000000,92.000000,40.000000,211.000000,2,0
31,2023,MONTGOMERY,0.490,0.510,0.484,0.516,0.723,0.099,0.002,0.079,...,0.828,0.034,0.065,0.120,2.000000,82.000000,54.000000,131.000000,0,0
32,2023,NORTHAMPTON,0.496,0.504,0.491,0.509,0.723,0.054,0.002,0.033,...,0.784,0.045,0.078,0.130,0.000000,63.000000,34.000000,59.000000,2,0
33,2023,NORTHUMBERLAND,0.511,0.489,0.508,0.492,0.891,0.020,0.000,0.006,...,0.716,0.028,0.122,0.169,0.000000,136.000000,32.000000,499.000000,1,1
34,2023,PHILADELPHIA,0.473,0.527,0.463,0.537,0.346,0.395,0.005,0.080,...,0.774,0.064,0.191,0.205,14.000000,69.000000,35.000000,93.000000,3,0
35,2023,SCHUYLKILL,0.515,0.485,0.519,0.481,0.862,0.033,0.002,0.005,...,0.736,0.057,0.126,0.204,0.000000,110.000000,33.000000,358.000000,1,1
36,2023,SOMERSET,0.518,0.482,0.519,0.481,0.942,0.022,0.000,0.007,...,0.743,0.054,0.108,0.192,61.000000,106.000000,18.000000,97.555556,1,1
37,2023,WASHINGTON,0.493,0.507,0.491,0.509,0.903,0.028,0.004,0.014,...,0.805,0.030,0.081,0.165,0.000000,74.000000,61.000000,96.000000,2,0
38,2023,WESTMORELAND,0.494,0.506,0.490,0.510,0.922,0.027,0.001,0.009,...,0.809,0.037,0.102,0.166,19.000000,108.000000,35.000000,89.000000,2,1
39,2023,YORK,0.498,0.502,0.492,0.508,0.802,0.053,0.001,0.014,...,0.835,0.036,0.075,0.166,0.000000,91.000000,22.000000,0.000000,2,1

In [3]:
# Swap position of 'Segment' and 'winning_party D:0 R:1' for concatenation alignment
# Switch columns 103 and 104
# Get the current column names
columns = county_2023.columns.tolist()

# Switch the positions of the 103rd and 104th columns
columns[102], columns[103] = columns[103], columns[102]

# Reorder the DataFrame & display
county_2023 = county_2023[columns]
county_2023

,Year,County,% Male,% Female,% Male > 18 Years Old,% Female > 18 Years Old,% White,% Black or African American,% American Indian and Alaska Native,% Asian,...,Nonveteran Labor Force Participation Rate (%),Nonveteran Unemployment Rate (%),% Nonveteran Population With Income Below Poverty Level (Past 12 Months),% Nonveteran Population With Any Disability,Birth Rate Per 1000 Women (15-19 Years Old),Birth Rate Per 1000 Women (20-34 Years Old),Birth Rate Per 1000 Women (35-50 Years Old),Received Public Assistance Income Rate Per 1000 Women (Past 12 Months),winning_party D:0 R:1,Segment
0,2023,ADAMS,0.492,0.508,0.490,0.510,0.882,0.013,0.004,0.008,...,0.821,0.035,0.079,0.141,0.000000,94.000000,49.000000,97.555556,1,2
1,2023,ALLEGHENY,0.488,0.512,0.482,0.518,0.759,0.125,0.001,0.042,...,0.811,0.039,0.110,0.144,9.000000,79.000000,35.000000,189.000000,0,0
2,2023,ARMSTRONG,0.499,0.501,0.497,0.503,0.951,0.006,0.000,0.001,...,0.769,0.027,0.106,0.186,30.000000,123.000000,9.000000,68.000000,1,1
3,2023,BEAVER,0.495,0.505,0.487,0.513,0.859,0.054,0.002,0.003,...,0.801,0.027,0.100,0.174,0.000000,67.000000,26.000000,222.000000,1,2
4,2023,BERKS,0.495,0.505,0.490,0.510,0.692,0.041,0.007,0.014,...,0.786,0.052,0.104,0.155,6.000000,102.000000,45.000000,57.000000,0,2
5,2023,BLAIR,0.497,0.503,0.492,0.508,0.905,0.024,0.000,0.008,...,0.757,0.032,0.147,0.189,0.000000,64.000000,49.000000,0.000000,1,1
6,2023,BUCKS,0.495,0.505,0.490,0.510,0.809,0.032,0.002,0.050,...,0.823,0.036,0.066,0.129,0.000000,84.000000,30.000000,199.000000,0,0
7,2023,BUTLER,0.498,0.502,0.494,0.506,0.928,0.009,0.003,0.014,...,0.781,0.043,0.087,0.145,0.000000,82.000000,34.000000,0.000000,0,2
8,2023,CAMBRIA,0.498,0.502,0.494,0.506,0.906,0.032,0.000,0.004,...,0.748,0.042,0.120,0.216,7.000000,107.000000,39.000000,27.000000,1,1
9,2023,CARBON,0.510,0.490,0.508,0.492,0.872,0.023,0.016,0.007,...,0.773,0.065,0.118,0.200,6.589744,89.384615,32.102564,97.555556,1,1
10,2023,CENTRE,0.521,0.479,0.524,0.476,0.839,0.037,0.001,0.063,...,0.650,0.036,0.212,0.132,0.000000,74.000000,60.000000,59.000000,0,1
11,2023,CHESTER,0.495,0.505,0.492,0.508,0.764,0.051,0.000,0.070,...,0.836,0.029,0.061,0.109,2.000000,69.000000,50.000000,157.000000,0,0
12,2023,CLEARFIELD,0.521,0.479,0.522,0.478,0.935,0.022,0.001,0.003,...,0.734,0.020,0.155,0.192,11.000000,80.000000,28.000000,0.000000,1,1
13,2023,COLUMBIA,0.488,0.512,0.485,0.515,0.912,0.018,0.001,0.016,...,0.788,0.057,0.119,0.114,0.000000,48.000000,8.000000,97.555556,1,2
14,2023,CRAWFORD,0.493,0.507,0.491,0.509,0.934,0.015,0.001,0.003,...,0.752,0.031,0.112,0.191,0.000000,69.000000,15.000000,0.000000,1,1
15,2023,CUMBERLAND,0.497,0.503,0.494,0.506,0.811,0.043,0.000,0.057,...,0.813,0.028,0.084,0.143,0.000000,84.000000,24.000000,0.000000,0,2
16,2023,DAUPHIN,0.489,0.511,0.482,0.518,0.624,0.185,0.006,0.070,...,0.815,0.046,0.114,0.152,0.000000,100.000000,24.000000,27.000000,0,2
17,2023,DELAWARE,0.485,0.515,0.477,0.523,0.626,0.225,0.001,0.062,...,0.788,0.060,0.102,0.154,26.000000,81.000000,38.000000,31.000000,0,0
18,2023,ERIE,0.503,0.497,0.494,0.506,0.829,0.077,0.001,0.021,...,0.740,0.040,0.130,0.190,0.000000,91.000000,45.000000,27.000000,0,1
19,2023,FAYETTE,0.497,0.503,0.495,0.505,0.902,0.039,0.001,0.005,...,0.699,0.036,0.179,0.225,0.000000,121.000000,15.000000,94.000000,1,1
20,2023,FRANKLIN,0.491,0.509,0.489,0.511,0.856,0.025,0.002,0.013,...,0.807,0.046,0.078,0.178,0.000000,123.000000,13.000000,186.000000,1,2
21,2023,INDIANA,0.500,0.500,0.500,0.500,0.931,0.027,0.000,0.003,...,0.686,0.056,0.167,0.183,0.000000,114.000000,17.000000,0.000000,1,1
22,2023,LACKAWANNA,0.493,0.507,0.484,0.516,0.803,0.037,0.000,0.032,...,0.738,0.029,0.164,0.198,9.000000,109.000000,25.000000,193.000000,0,1
23,2023,LANCASTER,0.490,0.510,0.484,0.516,0.807,0.038,0.002,0.022,...,0.826,0.031,0.076,0.149,1.000000,117.000000,61.000000,110.000000,1,2
24,2023,LAWRENCE,0.488,0.512,0.482,0.518,0.891,0.044,0.001,0.003,...,0.754,0.043,0.129,0.200,20.000000,67.000000,25.000000,0.000000,1,1
25,2023,LEBANON,0.495,0.505,0.488,0.512,0.809,0.031,0.000,0.021,...,0.828,0.022,0.078,0.146,0.000000,80.000000,21.000000,74.000000,0,2
26,2023,LEHIGH,0.493,0.507,0.487,0.513,0.613,0.062,0.007,0.039,...,0.795,0.048,0.110,0.150,0.000000,71.000000,30.000000,39.000000,0,2
27,2023,LUZERNE,0.499,0.501,0.496,0.504,0.744,0.051,0.003,0.013,...,0.752,0.047,0.150,0.191,0.000000,83.000000,22.000000,134.000000,1,1
28,2023,LYCOMING,0.493,0.507,0.489,0.511,0.885,0.032,0.008,0.009,...,0.783,0.048,0.118,0.188,40.000000,105.000000,17.000000,22.000000,1,1
29,2023,MERCER,0.497,0.503,0.490,0.510,0.884,0.042,0.002,0.006,...,0.737,0.051,0.104,0.170,0.000000,67.000000,34.000000,61.000000,1,1
30,2023,MONROE,0.510,0.490,0.499,0.501,0.626,0.144,0.002,0.027,...,0.770,0.067,0.089,0.186,0.000000,92.000000,40.000000,211.000000,0,2
31,2023,MONTGOMERY,0.490,0.510,0.484,0.516,0.723,0.099,0.002,0.079,...,0.828,0.034,0.065,0.120,2.000000,82.000000,54.000000,131.000000,0,0
32,2023,NORTHAMPTON,0.496,0.504,0.491,0.509,0.723,0.054,0.002,0.033,...,0.784,0.045,0.078,0.130,0.000000,63.000000,34.000000,59.000000,0,2
33,2023,NORTHUMBERLAND,0.511,0.489,0.508,0.492,0.891,0.020,0.000,0.006,...,0.716,0.028,0.122,0.169,0.000000,136.000000,32.000000,499.000000,1,1
34,2023,PHILADELPHIA,0.473,0.527,0.463,0.537,0.346,0.395,0.005,0.080,...,0.774,0.064,0.191,0.205,14.000000,69.000000,35.000000,93.000000,0,3
35,2023,SCHUYLKILL,0.515,0.485,0.519,0.481,0.862,0.033,0.002,0.005,...,0.736,0.057,0.126,0.204,0.000000,110.000000,33.000000,358.000000,1,1
36,2023,SOMERSET,0.518,0.482,0.519,0.481,0.942,0.022,0.000,0.007,...,0.743,0.054,0.108,0.192,61.000000,106.000000,18.000000,97.555556,1,1
37,2023,WASHINGTON,0.493,0.507,0.491,0.509,0.903,0.028,0.004,0.014,...,0.805,0.030,0.081,0.165,0.000000,74.000000,61.000000,96.000000,0,2
38,2023,WESTMORELAND,0.494,0.506,0.490,0.510,0.922,0.027,0.001,0.009,...,0.809,0.037,0.102,0.166,19.000000,108.000000,35.000000,89.000000,1,2
39,2023,YORK,0.498,0.502,0.492,0.508,0.802,0.053,0.001,0.014,...,0.835,0.036,0.075,0.166,0.000000,91.000000,22.000000,0.000000,1,2

In [4]:
# Combined 2012, 2016, 2019 dataset
county_2012_2016_2019 = pd.read_csv("Resources/County_Final_With_Outcomes_And_Segments.csv")
county_2012_2016_2019

,Year,County,% Male,% Female,% Male > 18 Years Old,% Female > 18 Years Old,% White,% Black or African American,% American Indian and Alaska Native,% Asian,...,Nonveteran Labor Force Participation Rate (%),Nonveteran Unemployment Rate (%),% Nonveteran Population With Income Below Poverty Level (Past 12 Months),% Nonveteran Population With Any Disability,Birth Rate Per 1000 Women (15-19 Years Old),Birth Rate Per 1000 Women (20-34 Years Old),Birth Rate Per 1000 Women (35-50 Years Old),Received Public Assistance Income Rate Per 1000 Women (Past 12 Months),winning_party D:0 R:1,Segment
0,2012,ADAMS,0.492,0.508,0.486,0.514,0.964249,0.020429,0.005107,0.010215,...,0.801,0.055,0.086,0.151,82.0,100.0,14.0,99.0,1,1
1,2012,ALLEGHENY,0.480,0.520,0.473,0.527,0.815505,0.142296,0.006869,0.035329,...,0.783,0.074,0.118,0.141,11.0,83.0,19.0,184.0,0,1
2,2012,ARMSTRONG,0.496,0.504,0.493,0.507,0.977205,0.013875,0.005946,0.002973,...,0.750,0.085,0.122,0.192,38.0,90.0,5.0,155.0,1,0
3,2012,BEAVER,0.483,0.517,0.477,0.523,0.913300,0.074877,0.004926,0.006897,...,0.786,0.083,0.100,0.162,40.0,121.0,15.0,26.0,1,0
4,2012,BERKS,0.491,0.509,0.484,0.516,0.907676,0.063278,0.010373,0.018672,...,0.796,0.095,0.127,0.142,13.0,109.0,20.0,174.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2020,SCHUYLKILL,0.515,0.485,0.513,0.487,0.946429,0.039683,0.005952,0.007937,...,0.726,0.048,0.113,0.186,9.0,159.0,25.0,64.0,1,0
116,2020,SOMERSET,0.522,0.478,0.524,0.476,0.951819,0.032448,0.008850,0.006883,...,0.702,0.026,0.097,0.189,113.0,162.0,44.0,102.0,1,0
117,2020,WASHINGTON,0.491,0.509,0.486,0.514,0.934378,0.047013,0.003918,0.014691,...,0.774,0.049,0.097,0.185,0.0,97.0,7.0,110.0,1,1
118,2020,WESTMORELAND,0.491,0.509,0.485,0.515,0.947835,0.035433,0.003937,0.012795,...,0.786,0.042,0.100,0.163,13.0,98.0,31.0,17.0,1,1
119,2020,YORK,0.496,0.504,0.488,0.512,0.894373,0.078973,0.007897,0.018756,...,0.799,0.037,0.087,0.138,8.0,84.0,25.0,162.0,1,1

In [5]:
# Concatenate both datasets vertically to form a single complete county dataset
combined_df = pd.concat([county_2012_2016_2019, county_2023], ignore_index=True)
combined_df

,Year,County,% Male,% Female,% Male > 18 Years Old,% Female > 18 Years Old,% White,% Black or African American,% American Indian and Alaska Native,% Asian,...,Nonveteran Labor Force Participation Rate (%),Nonveteran Unemployment Rate (%),% Nonveteran Population With Income Below Poverty Level (Past 12 Months),% Nonveteran Population With Any Disability,Birth Rate Per 1000 Women (15-19 Years Old),Birth Rate Per 1000 Women (20-34 Years Old),Birth Rate Per 1000 Women (35-50 Years Old),Received Public Assistance Income Rate Per 1000 Women (Past 12 Months),winning_party D:0 R:1,Segment
0,2012,ADAMS,0.492,0.508,0.486,0.514,0.964249,0.020429,0.005107,0.010215,...,0.801,0.055,0.086,0.151,82.0,100.0,14.0,99.000000,1,1
1,2012,ALLEGHENY,0.480,0.520,0.473,0.527,0.815505,0.142296,0.006869,0.035329,...,0.783,0.074,0.118,0.141,11.0,83.0,19.0,184.000000,0,1
2,2012,ARMSTRONG,0.496,0.504,0.493,0.507,0.977205,0.013875,0.005946,0.002973,...,0.750,0.085,0.122,0.192,38.0,90.0,5.0,155.000000,1,0
3,2012,BEAVER,0.483,0.517,0.477,0.523,0.913300,0.074877,0.004926,0.006897,...,0.786,0.083,0.100,0.162,40.0,121.0,15.0,26.000000,1,0
4,2012,BERKS,0.491,0.509,0.484,0.516,0.907676,0.063278,0.010373,0.018672,...,0.796,0.095,0.127,0.142,13.0,109.0,20.0,174.000000,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,2023,SCHUYLKILL,0.515,0.485,0.519,0.481,0.862000,0.033000,0.002000,0.005000,...,0.736,0.057,0.126,0.204,0.0,110.0,33.0,358.000000,1,1
156,2023,SOMERSET,0.518,0.482,0.519,0.481,0.942000,0.022000,0.000000,0.007000,...,0.743,0.054,0.108,0.192,61.0,106.0,18.0,97.555556,1,1
157,2023,WASHINGTON,0.493,0.507,0.491,0.509,0.903000,0.028000,0.004000,0.014000,...,0.805,0.030,0.081,0.165,0.0,74.0,61.0,96.000000,0,2
158,2023,WESTMORELAND,0.494,0.506,0.490,0.510,0.922000,0.027000,0.001000,0.009000,...,0.809,0.037,0.102,0.166,19.0,108.0,35.0,89.000000,1,2
159,2023,YORK,0.498,0.502,0.492,0.508,0.802000,0.053000,0.001000,0.014000,...,0.835,0.036,0.075,0.166,0.0,91.0,22.0,0.000000,1,2

In [6]:
# Export
combined_df.to_csv("Resources/Complete_County_Dataset.csv")